package org.skyforce.demon.player;

public enum TechniqueType {
    FLAME_BREATHING,
    WATER_BREATHING,
    THUNDER_BREATHING,
    WIND_BREATHING,
    MIST_BREATHING,
    STONE_BREATHING,
    SOUND_BREATHING,
    LOVE_BREATHING,
    SERPENT_BREATHING,
    SUN_BREATHING,
    BEAST_BREATHING,
    MOON_BREATHING,
    GALAXY_BREATHING,
    INSECT_BREATHING,
    FLOWER_BREATHING
}
